"""Expert local-trade one-pager — conversion on a shop phone, not Awwwards."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import List
from urllib.parse import quote_plus

PRICE = 5500
DEPOSIT = 2750
TRADE_HINT = re.compile(
    r"\b(plumb|electr|geyser|builder|carpenter|welder|panel.?beat|mechanic|"
    r"auto|workshop|tiler|roofer|painter|locksmith|aircon|hvac|gardener|"
    r"landscap|bakery|butcher|salon|hair|cafe|gym)\b",
    re.I,
)
HEADLINE = {
    "plumb": "Burst pipe or cold geyser — call us in {city}",
    "electr": "Power off? Call an electrician in {city}",
    "geyser": "Geyser down — call {name}",
    "mechanic": "The workshop in {city} that answers the phone",
    "auto": "The workshop in {city} that answers the phone",
    "workshop": "The workshop in {city} that answers the phone",
    "salon": "{name} — {city}",
    "hair": "{name} — {city}",
    "cafe": "{name} in {city}",
    "bakery": "{name} in {city}",
}


@dataclass
class TradeFacts:
    name: str
    city: str = "Kempton Park"
    trade: str = ""
    phone: str = ""
    hours: str = ""
    address: str = ""
    services: List[str] = field(default_factory=list)
    note: str = ""
    photos: List[str] = field(default_factory=list)

    def missing(self) -> List[str]:
        gaps = []
        if not self.phone:
            gaps.append("PHONE")
        if not self.hours:
            gaps.append("HOURS")
        if not self.trade:
            gaps.append("TRADE")
        return gaps


def is_trade_brief(text: str) -> bool:
    return bool(TRADE_HINT.search(text or ""))


def facts_from_text(name: str, blob: str, city: str = "Kempton Park") -> TradeFacts:
    phone = ""
    m = re.search(r"(0\d{2}[\s-]?\d{3}[\s-]?\d{4}|\+27[\s-]?\d{2}[\s-]?\d{3}[\s-]?\d{4})", blob or "")
    if m:
        phone = re.sub(r"\s+", " ", m.group(1)).strip()
    hours = ""
    hm = re.search(r"\b(\d{1,2}[:.]\d{2}\s*[-to]+\s*\d{1,2}[:.]\d{2}|\bMon\b.+\bSat\b)", blob or "", re.I)
    if hm:
        hours = hm.group(0)
    trade = ""
    tm = TRADE_HINT.search(f"{name} {blob}")
    if tm:
        trade = tm.group(1)
    return TradeFacts(name=name.strip() or "Shop", city=city, trade=trade, phone=phone, hours=hours, note=(blob or "")[:400])


def _esc(s: object) -> str:
    return (
        str(s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _headline(facts: TradeFacts) -> str:
    key = (facts.trade or "").lower()
    for k, tmpl in HEADLINE.items():
        if k in key:
            return tmpl.format(city=facts.city.split(",")[0], name=facts.name)
    return f"{facts.name} in {facts.city.split(',')[0]}"


def _wa(phone: str) -> str:
    tel = re.sub(r"\D", "", phone or "")
    if tel.startswith("0") and len(tel) == 10:
        return "27" + tel[1:]
    return tel


def _schema(facts: TradeFacts) -> str:
    payload = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": facts.name,
        "address": {"@type": "PostalAddress", "addressLocality": facts.city, "addressCountry": "ZA"},
    }
    if facts.phone:
        payload["telephone"] = facts.phone
    if facts.address:
        payload["address"]["streetAddress"] = facts.address
    if facts.hours:
        payload["openingHours"] = facts.hours
    # A shop name carrying "</script>" would otherwise close the ld+json block
    # early and let the rest of the name run as markup.
    return (
        json.dumps(payload, ensure_ascii=False)
        .replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
    )


def render_trade_html(facts: TradeFacts, *, include_sku: bool = False, live: bool = False) -> str:
    phone = facts.phone or "[PHONE]"
    hours = facts.hours or "[HOURS]"
    trade = facts.trade or "local trade"
    wa = _wa(facts.phone)
    gaps = facts.missing()
    headline = _headline(facts)
    maps = (
        f"https://maps.google.com/?q={quote_plus(facts.address + ' ' + facts.city + ' South Africa')}"
        if facts.address else ""
    )
    robots = "index,follow" if live else "noindex,nofollow"
    miss = (" — missing: " + ", ".join(gaps)) if gaps else ""
    banner = "" if live else f"<div class='banner'>Internal mockup{miss} · print · not live</div>"
    marker = "" if live else "\n<!-- INTERNAL MOCKUP — adviser review required; not live. Generated by Fortitudo AI. -->"
    sku = f"<p>Fortitudo Studios: R{PRICE:,} once, R{DEPOSIT:,} to start.</p>" if include_sku and not live else ""
    services = "".join(f"<li>{_esc(s)}</li>" for s in (facts.services[:6] or [trade]))
    photos = "".join(f"<img src='{_esc(p)}' alt='{_esc(facts.name)}'>" for p in facts.photos[:3])
    shots = f"<div class='shots'>{photos}</div>" if photos else ""
    maps_html = f"<a href='{maps}'>Open in Maps</a>" if maps else ""
    tel_digits = re.sub(r"\D", "", facts.phone or "")
    tel = f"tel:{tel_digits}" if tel_digits else "#phone"
    addr_block = f"<div><strong>Address</strong> {_esc(facts.address)} {maps_html}</div>" if facts.address else ""
    return f"""<!DOCTYPE html>{marker}
<html lang="en-ZA">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="{robots}"><meta name="theme-color" content="#111111">
<title>{_esc(facts.name)} · {_esc(trade)} · {_esc(facts.city)}</title>
<meta name="description" content="{_esc(headline)}. Call {_esc(phone)}.">
<script type="application/ld+json">{_schema(facts)}</script>
<style>
:root{{--bg:#111;--ink:#f4efe6;--mute:#b7b0a4;--line:#2a2a2a;--btn:#f0ece3;--btnink:#111}}
*{{box-sizing:border-box}}html,body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.5 system-ui,sans-serif}}
.banner{{background:#3a2e18;color:#f0d27a;text-align:center;font-size:.78rem;padding:.55rem}}
.wrap{{max-width:640px;margin:0 auto;padding:1.25rem 1.15rem 6.5rem}}
.kicker{{letter-spacing:.16em;text-transform:uppercase;font-size:.68rem;color:var(--mute)}}
h1{{font-size:clamp(1.7rem,6vw,2.35rem);line-height:1.15;letter-spacing:-.03em;margin:.2rem 0 .75rem}}
.lead{{color:var(--mute);margin:0 0 1.2rem}}
.actions,.dock{{display:flex;gap:.55rem}}
.btn{{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:.75rem 1.1rem;border-radius:999px;background:var(--btn);color:var(--btnink);font-weight:700;text-decoration:none}}
.btn.ghost{{background:transparent;color:var(--ink);border:1px solid var(--line)}}
.nap{{padding:1rem 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);color:var(--mute)}}
.shots img{{width:100%;height:auto;border-radius:10px;margin:.4rem 0}}
h2{{font-size:.8rem;letter-spacing:.08em;text-transform:uppercase;color:var(--mute)}}
.dock{{position:fixed;left:0;right:0;bottom:0;padding:.65rem .75rem calc(.65rem + env(safe-area-inset-bottom));background:rgba(17,17,17,.94);border-top:1px solid var(--line)}}
.dock a{{flex:1}}
@media print{{.banner,.dock{{display:none}}body{{background:#fff;color:#111}}}}
</style></head>
<body>
{banner}
<main class="wrap">
<p class="kicker">{_esc(facts.city)} · {_esc(trade)}</p>
<h1>{_esc(headline)}</h1>
<p class="lead">Call or WhatsApp. The number is on this page.</p>
<div class="actions"><a class="btn" href="{tel}">Call {_esc(phone)}</a><a class="btn ghost" href="https://wa.me/{_esc(wa)}">WhatsApp</a></div>
{shots}
<div class="nap"><div><strong>Phone</strong> {_esc(phone)}</div><div><strong>Hours</strong> {_esc(hours)}</div>
{addr_block}</div>
<h2>Work</h2><ul>{services}</ul>
<footer style="margin-top:2rem;color:#b7b0a4;font-size:.8rem"><p>{_esc(facts.name)} · {_esc(facts.city)}</p>{sku}</footer>
</main>
<div class="dock"><a class="btn" href="{tel}">Call</a><a class="btn ghost" href="https://wa.me/{_esc(wa)}">WhatsApp</a></div>
</body></html>
"""


def generate_trade_page(name: str, source_text: str, city: str = "Kempton Park") -> str:
    return render_trade_html(facts_from_text(name, source_text, city=city), include_sku=False)
