/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as DropzoneRouteImport } from './routes/dropzone'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SocialRouteImport } from './routes/social'
import { Route as AdjudicationIndexRouteImport } from './routes/adjudication/index'
import { Route as AdjudicationSessionIdRouteImport } from './routes/adjudication/$sessionId'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const DropzoneRoute = DropzoneRouteImport.update({
  id: '/dropzone',
  path: '/dropzone',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjudicationIndexRoute = AdjudicationIndexRouteImport.update({
  id: '/adjudication/',
  path: '/adjudication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjudicationSessionIdRoute = AdjudicationSessionIdRouteImport.update({
  id: '/adjudication/$sessionId',
  path: '/adjudication/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/craft': typeof CraftRoute
  '/dropzone': typeof DropzoneRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/social': typeof SocialRoute
  '/adjudication/$sessionId': typeof AdjudicationSessionIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/adjudication/': typeof AdjudicationIndexRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/craft': typeof CraftRoute
  '/dropzone': typeof DropzoneRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/social': typeof SocialRoute
  '/adjudication/$sessionId': typeof AdjudicationSessionIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/adjudication': typeof AdjudicationIndexRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/craft': typeof CraftRoute
  '/dropzone': typeof DropzoneRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/social': typeof SocialRoute
  '/adjudication/$sessionId': typeof AdjudicationSessionIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/adjudication/': typeof AdjudicationIndexRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/chat'
    | '/craft'
    | '/dropzone'
    | '/learn'
    | '/library'
    | '/social'
    | '/adjudication/$sessionId'
    | '/clients/$clientId'
    | '/adjudication/'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/chat'
    | '/craft'
    | '/dropzone'
    | '/learn'
    | '/library'
    | '/social'
    | '/adjudication/$sessionId'
    | '/clients/$clientId'
    | '/adjudication'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/chat'
    | '/craft'
    | '/dropzone'
    | '/learn'
    | '/library'
    | '/social'
    | '/adjudication/$sessionId'
    | '/clients/$clientId'
    | '/adjudication/'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  ChatRoute: typeof ChatRoute
  CraftRoute: typeof CraftRoute
  DropzoneRoute: typeof DropzoneRoute
  LearnRoute: typeof LearnRoute
  LibraryRoute: typeof LibraryRoute
  SocialRoute: typeof SocialRoute
  AdjudicationSessionIdRoute: typeof AdjudicationSessionIdRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  AdjudicationIndexRoute: typeof AdjudicationIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropzone': {
      id: '/dropzone'
      path: '/dropzone'
      fullPath: '/dropzone'
      preLoaderRoute: typeof DropzoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjudication/': {
      id: '/adjudication/'
      path: '/adjudication'
      fullPath: '/adjudication/'
      preLoaderRoute: typeof AdjudicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjudication/$sessionId': {
      id: '/adjudication/$sessionId'
      path: '/adjudication/$sessionId'
      fullPath: '/adjudication/$sessionId'
      preLoaderRoute: typeof AdjudicationSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  ChatRoute: ChatRoute,
  CraftRoute: CraftRoute,
  DropzoneRoute: DropzoneRoute,
  LearnRoute: LearnRoute,
  LibraryRoute: LibraryRoute,
  SocialRoute: SocialRoute,
  AdjudicationSessionIdRoute: AdjudicationSessionIdRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  AdjudicationIndexRoute: AdjudicationIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
